### ISSUE TITLE
Missing dependency for newsrss/rss?

### ISSUE THREAD

**Issue by ghost** [openSUSE/www-o-o#15]
Trying to build/serve this website locally, I get

`  Dependency Error: Yikes! It looks like you don't have .../www-o-o/_plugins/newsrss.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the ...www-o-o/_plugins/newsrss.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- rss' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
`

There is a newsrss.rb in the plugin folder but maybe the dependency for rss isn't properly declared so it doesn't pull it in?

**Comment by hellcp** [comment]
There have been some changes to what is shipped with Ruby 3, so an error like that isn't entirely unexpected. I have fixed it by adding rss to the Gemfile
