### ISSUE TITLE
Jekyll or something else?

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/www-o-o#3]
Our Jekyll theme now support localization. It works very well for sites like this (no archives). Compared to the old one, which uses JS localization, Jekyll localization is more SEO friendly, meaning more users can reach the site from search engines.

**Comment by hellcp** [comment]
Yes

**Comment by vinzv** [comment]
Yes please. The less JS the better as improves loading times as well.

**Comment by hellcp** [comment]
Since the site is already using jekyll, this can be closed
